version: '3'
services:
  db:
    image: postgres:14.2
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    networks:
      - internal_network
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=yondero'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'


  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
    internal: true
  external_network:

volumes:
  db_data: