version: '3'
services:
  db:
    image: postgres:14.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal_network
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=yondero'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./data/attatchmnents:/data/attatchments
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal_network
      - external_network
    command: sh -c ". ~/.profile && poetry run gunicorn run:app --config /app/config/gunicorn.conf.py"

networks:
  internal_network:
    internal: true
  external_network:
